language: ruby
rvm:
  - 1.9.3

gemfile: Gemfile

bundler_args: --path=vendor/bundle

before_script:
  - sh -c "psql -c 'create database ffcrm_mingle_test;' -U postgres"
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"

# Run specs, acceptance tests, and ensure that assets can compile without errors
script: "bundle exec rake"
