language: ruby
rvm:
  - 2.2.1

gemfile: Gemfile

bundler_args: --path=vendor/bundle

before_script:
  - sh -c "psql -c 'create database ffcrm_mingle_test;' -U postgres"

# Run specs, acceptance tests, and ensure that assets can compile without errors
script: "bundle exec rake"
